# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-19 12:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendaritem',
            name='date',
            field=models.DateField(default=datetime.date(2016, 9, 19)),
        ),
    ]
